### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by Kusken** [Kusken/open-blog#2]

**Comment by Kusken** [comment]
# Roles:
**Blog author**
- [ ] Only blog authors can post blog posts
- [ ] Only blog authors can update blog posts
- [ ] Only blog authors can remove blog posts
